version: '3'
services:
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  emqtt:
    image: emq:frombase
    ports:
      - "1883:1883"
      - "3000:18083"
    # environment:
      # EMQ_LOADED_PLUGINS: 'emq_recon,emq_retainer,emq_dashboard'
    #   # EMQ_AUTH__REDIS__SERVER: redis:6379
      # EMQ_BRIDGE__KAFKA__SERVER: '35.159.7.143:9092'